### PR TITLE
Add Java Record support

### LINKED ISSUE #51: Support Java Records
Support the new Record language feature. Should behave pretty much just like POJOs. Main obstacle is getting the annotations from the constructor

### PR DESCRIPTION
**Pull request by ivangreene**
Co-authored with @buchananwill

I'm opening this to do review, add tests, and make some changes.

Resolves #51

### CODE REVIEW

**Comment by buchananwill** [comment]
Cool, I think my next pull request will cover all this. Do you want me to add tests within that PR? I would expect to test:

- schema is generated correctly to match an equivalent declared as a class
- any annotations currently supported are picked up from the constructor params same as class field declarations

My current implementation does these.

**Comment by ivangreene** [comment]
@buchananwill I don't mind adding some tests here. I have some free time today so I'm going to go through and work on a few of these. I think the most useful thing at this stage is if you can figure out a way to write tests for the Gradle plugin? I don't know how to do that

**Comment by ivangreene** [comment]
@buchananwill I've cleaned this up and added tests that match a POJO test. Please let me know what you think. I can release this today unless you have any concerns that I should address

**Comment by buchananwill** [comment]
Cool, I've had quick read through the TypeDescriptor class and test and
that all looks good. I'll be at a birthday party for the rest of the day
(mine, plus my sister in laws' who have birthdays this week also!) so
probably won't get a chance to do any work till tomorrow.

I'm happy for you to release though if it meets your satisfaction. 👍

**Comment by ivangreene** [comment]
@buchananwill I merged the code, but the release was botched due to something changing with the Maven central repository. I'll look into that later

**Comment by ivangreene** [comment]
This has been released in version 0.6.1

**Pull request merged**
