### PR TITLE
Adding Gradle Plugin and support for Java Records, Maps, and OptionalAnnotations.

### PR DESCRIPTION
**Pull request by buchananwill**
Hi,

Really great package building on the Typescript generator. I'd written myself a workable module from scratch a few months back (before yours was listed on the zod page), but hadn't yet implemented annotations and other features. Thanks for making this! You may not want to accept all the additions I've made here, but I'll go through them.

I haven't used Maven before - only Gradle - so I added a Gradle plugin mirroring your Maven one. I wasn't sure how to run that build within the maven project setup though. It's currently a single class "PojoParser" just sitting in the root src of the core module.

I needed a few other features as well, such as Maps and Records, which required changing the language target up, so I set it to 17 which is what I generally take as a baseline.

I did also make a couple of changes which are different opinion rather than need: specifically how nullables/optionals are handled.  To this end, I added the existing OptionalAnnotations setting already present in the Typescript-generator, and made that the test for adding .optional().nullable() to the generated classes. You may want to revert that to your previous default, but I thought it might be good to make available as a user setting? I personally prefer to leave all fields without zod's nullish attributes, unless I've specified those within the Java DTO. It's tricky to reconcile Jackson de-serialization (which inherently erases a distinction between absent/null properties), and request validation. I prefer my Zod schemas to assume required unless told otherwise, but adding NotNull to DTOs conflicts with allowing Jackson to de-serialize missing properties in certain scenarios. My current behaviour of the JavaToZodParser is: Nullable (via javax) -> .optional().nullable(), no annotation -> normal Zod property.

I also changed the behaviour when it can't find the name for a type. Instead of throwing an error, it now returns the zod any type, which it will include in the schema, but also logs that to the console. I found this more helpful for troubleshooting than a hard refusal, since it meant I could still inspect the output and try to pinpoint anything that was missing. I was using slf4j in my own codebase, but since that wasn't a dependency already here I swapped it to just a basic console log.

Hope some of this at least is useful for you to incorporate into the main repo!
Will

### CODE REVIEW

**Comment by ivangreene** [comment]
Hi @buchananwill , thanks for the contribution! If you could split these into independent PRs that each represent a single feature, I would be happy to review them. As it stands, I'm afraid this is too many changes to review in a single PR

As for individual features you've mentioned, I think I'm interested in all of them.

The relevant existing issue for nullability: #31 . I have discussed some concerns there

For the gradle plugin, that should be put into its own module (a separate directory at the root of the project, like the Maven plugin). The core module is meant to be made up of classes that can be reused as a library by other codebases

Language target: that is currently configured here: https://github.com/ivangreene/java-to-zod/blob/main/pom.xml#L50-L52 Please set these properties in the root pom rather than in the submodule

**Comment by ivangreene** [comment]
Please also run the Maven build locally (`./mvnw -B package`). There are a lot of formatting changes that will be caught with the Spotless plugin and can be fixed (it will show the command to fix them)

**Comment by buchananwill** [comment]
Thanks. I will go over these issues and split the changes up.

Speak soon.

**Comment by buchananwill** [comment]
Thanks again for the pointers. I've gone through the groundwork on this
now. I have a working Gradle plugin in my mavenLocal that parses schemas in
my main project. So, next step will be splitting apart the changes and
ordering them so the updates make sense. Nice job, btw, on the
compartmentalization of the modules - made it easy to add the Gradle
support as a distinct entity.

On the nullability issue: would you accept leveraging the Typescript
Generator settings as an override? E.g. the default output is
optional().nullable() as you've configured, however if there are any
optionalAnnotations or nullableAnnotations passed in as a setting, this
will be overridden, and then only the fields marked with one of the
designated annotations will be given the relevant attributes. This would
give the user much more control over whether a schema should allow optional
or nullable independently, without breaking the current behaviour (since
these two settings weren't currently being observed by the
JavaToZodConvertor).

https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#optionalAnnotations

Will

**Comment by ivangreene** [comment]
@buchananwill let's discuss the nullability issue in the open issue for it: #31 
I will try to make some time this weekend to dig in and give an opinion on what makes sense there. At first glance, your idea to use optionalAnnotations makes sense, but it's been a while since I've been in this codebase to consider all perspectives

**Comment by buchananwill** [comment]
Ok, I split into seven pull requests to document the scope of each change. No rush/pressure for reviewing! The Gradle plugin is working locally for me now, so thanks very much with your help of setting up the Maven environment.

I will need to come back around on a couple of things like the Map support, ( see [https://github.com/ivangreene/java-to-zod/issues/8](url) and there is some detail to add on the optional/nullable handling.

**Comment by ivangreene** [comment]
@buchananwill thanks. It looks like the PRs each have more than intended in them. Some of this appears due to wanting to use stacked PRs to take advantage of the other features (e.g Java 17 support is needed for Records). It seems like this is not supported from forks: https://stackoverflow.com/questions/72697631/stacked-pull-requests-from-the-fork-to-the-parent-repository

So I think the best option will be to open the ones that can go independently now, making sure they only have the intended changes in them, and after I merge those, you can open the ones that need to be stacked

**Comment by buchananwill** [comment]
Let me close all those, and I'll split them up further.

**Pull request closed without merging**
